### ISSUE TITLE
Decompress Tools Documentation

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#38]
The TrID plug-in's documentation mentions that TrID must be installed...

> Note: TRiD binary and definitions need to be installed for this plugin to operate properly.

 The Decompression plug-in fails to mention that in it's default configuration it needs...

- 7z
- upx
- gzip
- tar
- ace

...also since 7z supports: tar, and gzip it might be preferable to minimize the number of dependencies by utilizing 7z for those types as well.

**Comment by mlaferrera** [comment]
Good point..I've updated the plugin as recommended above. Thanks again!

**Comment by Kolano** [comment]
The documentation also needs to purge the gzip/tar references under ARCHIVE_CMDS.
https://github.com/PUNCH-Cyber/stoq-plugins-public/tree/master/decompress
