### ISSUE TITLE
iocextract Documentation Error

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#40]
https://github.com/PUNCH-Cyber/stoq-plugins-public/tree/master/iocextract

The descriptions for the url and domain indicator types seem to be reversed, though they'll also seem to need some rewording, since "Pattern is identical to domain" isn't appropriate if transitioned to Domain.

**Comment by mlaferrera** [comment]
It could definitely use some clarification. I'll push up clarified documentation.

A `domain` for whitelisting will match against a domain, as well as the domain in a url.

A `url` will match against only the domain in a url, not the schema or uri.

**Comment by Kolano** [comment]
Yeah, that naming is confusing; domain matches against urls, and url doesn't.
