### ISSUE TITLE
suricata-dirmon

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#41]
Noticed there was a suricata-dirmon: https://github.com/PUNCH-Cyber/stoq-plugins-public/tree/3d792144e3cc65f3a3984bae10538b3baf55ce69/source/suricata-dirmon that doesn't seem to be publicized. It included this comment...

>         # A bit of a race condition here. Suricata writes a tmp file, until the stream is complete.
>         # At that point, suricata moves file to a filename minus the .tmp extension which is not
>         # detected by the filesystem as an on_created() event, thus we will never see it. Let's
>         # assume that if the file name ends with a ".tmp" extension, by the time we get to loading
>         # the file itself, suricata has finished writing to disk. Ugly? yes.

You can detect the finalized files being ready using the on_moved() event instead, which is what the renames should appear as.

**Comment by mlaferrera** [comment]
This plugin is still available for stoQ v1, but it was not ported over to v2. A lot has changed in the way suricata handles file extraction since the initial plugin was released and I haven't had a chance to port it over yet.
