### ISSUE TITLE
Decompress Meta-data

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#43]
The decompress plugin currently outputs nothing (besides additional payloads) when run...
```
"decompress": {}
```

It would be good to provide meta meta-data for archives. This could occur even if archives aren't or can't be extracted (i.e. too large to extract, or have other issues).

7z provides meta-data with...
```
7z l -slt file
```

The meta-data alone may be sufficient for analysis in some cases, so a mode to just extract meta-data without decompressing may also be useful.

**Comment by mlaferrera** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
