### ISSUE TITLE
File / binaries repository in support of unit tests

### ISSUE THREAD

**Issue by serializingme** [PUNCH-Cyber/stoq-plugins-public#45]
I'm looking into adding unit tests to the latest LIEF plugin, pull request #44, in order to be inline with issue #22 and I want to ask what would be the best approach to obtain the necessary test data:

1. Create a submodule on the data directory pointing to existing binary samples repositories, for example, [LIEF test samples](https://github.com/lief-project/samples) or [JonathanSalwan Binary Samples](https://github.com/JonathanSalwan/binary-samples)
1. Copy the binary samples from such repositories, but include the respective licensing information
1. Create stoQ own collection on a separate repository (e.g. `stoq-samples`) that would be linked to the data directory as a submodule and that could be used by other plugins like `peinfo`

I'm of the opinion that even though it would take longer, I'm inclined to go for the 3rd option.

Initial inputs to the discussion from @mlaferrera:

> That is really good question and one I've been grappling with. I think there is a lot of utility in creating a separate repo for test data, especially since there is overlap in filetypes amongst plugins. This would require a bit of testing to ensure there aren't complications with using a submodule. I've had some bad experiences using them, so I may seem be a bit apprehensive in their use. With that said, I'm not sure there is a better option.

The only problem I have with submodules is forgetting to update the reference to the latest version. Usually this means that the build breaks because there are submodule changes that are needed by the main project but such changes aren't available because it still references old submodule code :D

**Comment by mlaferrera** [comment]
Sorry for the delay in getting back to you on this. 

What are your thoughts on creating a new repository with just samples, that are a collective of the repositories listed above (and also contains the appropriate licenses), as well as custom test data for plugins as required? I think of all the options, I like this one the best as it allows plugin tests to leverage battle tested test data, respects their license model, and doesn't force a user to download 3rd party licensed data (unless they want to run tests).

**Comment by mlaferrera** [comment]
Yeah, I like that idea. I'll do a bit of research soon and try to collect a corpus. Thanks for the help!

**Comment by mlaferrera** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
