### ISSUE TITLE
Python Shebang?

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#48]
A minor nitpick here, only a limited set of plug-in files include a Python3 shebang (#!/usr/bin/env python3)...
- test_exif.py
- falcon-sandbox.py
- hash,py
- test_hash.py
- test_ssdeep.py
- test_javaclass.py
- mraptor.py
- ole.py
- opsway.py
- pecarve.py
- rtf.py
- smtp.py
- swfcarve.py
- symhash.py
- tika.py
- tnet.py
- vtmis-filefeed.py
- vtmis-search.py
- xpdcarve.py
- test_xorsearch.py
- test_yara.py
- yarascan

Further consistency to include it or not would probably be good.

**Comment by mlaferrera** [comment]
Thanks, @Kolano. This has no real negative impact on the use of the plugins, so I don't plan of making these changes en masse. I may over time though. Please feel free to submit a PR, help is always welcome and appreciated.
