### ISSUE TITLE
VTMIS-Search References Worker Data in Dispatcher?

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#51]
I'm confused by the VTMIS dispatcher...
```
    def get_dispatches(
        self, payload: Payload, request_meta: RequestMeta
    ) -> DispatcherResponse:
        """
        Check if `iocextract` plugin has results, if so, dispatch to `vtmis-search` worker

        """
        dr = DispatcherResponse()
        if 'iocextract' in payload.worker_results:
            dr.plugin_names.append('vtmis-search')
        return dr
```

It seems to references payload.worker_results, but I thought such were only available to Deep Dispatchers?

**Comment by mlaferrera** [comment]
Hi @Kolano -- a `Payload` object gets passed to `get_dispatches`, which may contain a `worker_results` object as can be seen [here](https://github.com/PUNCH-Cyber/stoq/blob/master/stoq/data_classes.py#L89).

To clarify what this plugin is doing, if there are `iocextract` results, send the payload to the `WorkerPlugin` `vtmis-search` for scanning, at which point it will grab the relevant IOCs (i.e., hashes, domains, etc..) and search VTMIS for them. If they are found in VTMIS, the results will be added to `StoqResponse`.

**Comment by Kolano** [comment]
OK, the documentation is confusing there...
https://stoq-framework.readthedocs.io/en/latest/dev/deepdispatchers.html
> Because deep dispatchers are handled after the worker plugins scan the payload, deep dispatchers are passed the original payload in addition to the scan results from the workers.

https://stoq-framework.readthedocs.io/en/latest/_images/workflow-72.png
Dispatcher is listed as occurring before any workers, so unclear how it can parse worker (i.e. ioextract) results.

- If dispatchers get payloads with worker data is their only difference that can be run multiple times per payload? Or that they can handle outputs from workers that were dispatched by dispatchers?
- It seems like iocextract should be dispatching to VTMIS, Again I think I'm confused about something with this, I understood dispatchers to determine workers to run, not to pull results from other workers.

**Comment by mlaferrera** [comment]
Yeah, I think you are correct in that I can make the documentation a bit clearer. The normal flow when using the `stoq` command line would not have anything in `Payload.worker_results`. However, the `Payload` object is what gets passed around, so if someone were to interact with the API for plugins directly (which is a normal use case), there could potentially be data in `Payload.worker_results`. A simple workflow for the `vtmis-search` `deep-dispatcher` plugin would be to perhaps parse an e-mail, extract iocs, then use `vtmis-search` as a `deep-dispatcher` to determine if any of the extracted IOC's are known to VTMIS. 

Does that help to make it a bit clearer?

**Comment by Kolano** [comment]
A bit, though I think I'm still unclear on why the multiple dispatcher types are needed if a dispatcher can get worker data. It seems to complicate things, and I'm still unclear what really differentiates them. Apparently Deep Dispatchers can run multiple times, but I'm not clear why a version that can't run repeatedly is needed.

**Comment by mlaferrera** [comment]
'Supposed to work' is a relative term. When we designed stoQ we tried to ensure we could maximize the flexibility of the framework for the user as well as the developer. In this specific instance with the `vtmis-search` plugin, the code is near identical. But it doesn't have to be that way. That is just one example.

Deep dispatchers are generally used for more advanced use cases. Most users will never have a use case for leveraging deep dispatching. They are really useful when iterative scanning needs to be done on payloads and/or their results *after* the initial scanning of a payload by worker plugins. In the case of the `vtmis-search` deep dispatcher, to check VTMIS for IOCs extracted by the `iocextract` worker plugin. 
 
Dispatching allows for a payload to be dynamically routed to plugins based on a set of rules. For instance, a yara rule that says a payload needs to be decompressed.

**Comment by Kolano** [comment]
It's confusing, particularly since there aren't other examples in the current public Plug-ins.

As things seemed to be documented:
Dispatcher: Routes payloads to workers based on the dispatchers analysis, occurs prior to initial workers
Deep Dispatcher: Routes payloads to workers based on the dispatchers analysis and other worker outputs, occurs post initial workers
(which still don't seem that different, worker_results would just be None in the first case)

**Comment by mlaferrera** [comment]
The definitions are accurate. The documentation certainly has room for clarification though. As I previously stated, deep dispatchers are:

> really useful when iterative scanning needs to be done on payloads and/or their results after the initial scanning of a payload by worker plugins.

This is fundamentally different from regular dispatcher plugins that are _intended_ to be used with a payload only. I highlight intended because the framework itself is designed to be extremely flexible. A _developer_ can ultimately decide otherwise if they choose to do so and design their own workflow around the framework and plugins.

Since the deep dispatcher use case is more specialized and not something that would be used by most users, there has not been a lot of effort in making publicly available plugins that demonstrate its use. We can work towards on open sourcing some deep dispatcher plugins that may help to clarify their utility.

**Comment by mlaferrera** [comment]
There is at least one other group that is using the plugin-in as is, so I'll be leaving it in for now.
