### ISSUE TITLE
Encoding Errors with VTMIS-Search / TrID

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#53]
I'm hitting a UnicodeEncodeError when trying to use the VTMIS-Search plugin against the attached zip or the exe inside it...
[dnetc.zip](https://github.com/PUNCH-Cyber/stoq-plugins-public/files/2929580/dnetc.zip)

The exe can be retrieved directly from the Distributed.net site if my upload is untrusted: http://http.distributed.net/pub/dcti/current-client/dnetc-win64-amd64.zip

```
LANG=/usr/lib/locale/C.UTF-8
stoq scan dnetc.zip -a decompress vtmis-search trid
Traceback (most recent call last):
  File "/home/user/.stoq/.venv/bin/stoq", line 11, in <module>
    sys.exit(main())
  File "/home/user/.stoq/.venv/lib/python3.6/site-packages/stoq/cli.py", line 271, in main
    print(response)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 7736: ordinal not in range(128)
```

```
LANG=/usr/lib/locale/C.UTF-8
stoq scan dnetc.exe -a vtmis-search trid
Traceback (most recent call last):
  File "/home/user/.stoq/.venv/bin/stoq", line 11, in <module>
    sys.exit(main())
  File "/home/user/.stoq/.venv/lib/python3.6/site-packages/stoq/cli.py", line 271, in main
    print(response)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 6549: ordinal not in range(128)
```

`LANG=/usr/lib/locale/C.UTF-8`
...seems to be required for the TrID plugin to run without this error...
```
    "errors": {
        "trid": [
            "trid: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.\n"
        ]
    },
```

**Comment by mlaferrera** [comment]
I'm unable to replicate this, it works fine when I run the exact same commands. Can you save the results to a file instead and share that with me?

For TRiD, you've already opened an issue for this (#37). This is a requirement for TRiD and doesn't have anything to do with stoQ, so there isn't anything I can do to fix that.

Please try not to mix issues into one ticket, it makes it extremely difficult to respond to them and also make it more difficult for future readers to track the conversation.

**Comment by Kolano** [comment]
OK, sorry, I opened this just against the VTMIS-Search issue, and realized it was related to the TrID issue afterward. I had forgotten reporting that since it was closed out.

**Comment by Kolano** [comment]
I can't submit a file with the issue, as when the error occurs no results are output only the exception traceback shown above. With the LANG env var unset I get this output with the TrID error...
[LANG_Not_Set.txt](https://github.com/PUNCH-Cyber/stoq-plugins-public/files/2929843/LANG_Not_Set.txt)

This occurs under Ubunutu 18.10, I can likely provide a deployment script to generate a duplicate environment if needed.

**Comment by mlaferrera** [comment]
You can use the `filedir` plugin to save the results:

`stoq run -P filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/`

**Comment by mlaferrera** [comment]
You can use the `filedir` plugin to save the results:

`stoq run -P filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/`

**Comment by Kolano** [comment]
There is no result output, I get...
```
stoq run -P filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/
[2019-03-05 11:01:25,263 INFO] stoq: Provider plugin filedir successfully completed
```
...and no file output is seen in ~/results.

**Comment by mlaferrera** [comment]
Sorry, helps to give you the right command. I didn't include a connector plugin so the results didn't get saved. Just make sure you update `dnetc.exe` to the correct location of the file you are scanning. A file with the results should in be `results/`.

``stoq run -P filedir -C filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/``

**Comment by Kolano** [comment]
OK, that still doesn't work out. A bunch of content is spit out to the stderr/stdout but nothing goes to the output file in results/. I was able to pipe the output to a file though.

**result/ output with LANG unset:**
```
stoq run -P filedir -C filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/
```
[LANG NOT SET ec965c06-2a38-45eb-bf7e-2612ba08950b.txt](https://github.com/PUNCH-Cyber/stoq-plugins-public/files/2931859/LANG.NOT.SET.ec965c06-2a38-45eb-bf7e-2612ba08950b.txt)

**result/ output with LANG set:**
```
LANG=/usr/lib/locale/C.UTF-8
stoq run -P filedir -C filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/
```

Empty file

**piped capture of output with LANG set:**
```
LANG=/usr/lib/locale/C.UTF-8
stoq run -P filedir -C filedir -a vtmis-search --plugin-opts filedir:source_dir=dnetc.exe filedir:results_dir=results/ &> test.txt
```
[LANG SET pipe.txt](https://github.com/PUNCH-Cyber/stoq-plugins-public/files/2931869/LANG.SET.pipe.txt)

**Comment by mlaferrera** [comment]
That worked, I just needed to know what the data coming back looked like. It didn't write to a file because there was an exception, which is expected behavior. 

This appears to be an oddity with your environment and TRiD. Try setting `LC_ALL=C` and `LANG=en_US` (which is the default for Ubuntu 18.10).

**Comment by Kolano** [comment]
With `LC_ALL=C` and `LANG=en_US ` set the trid plugin will run, but I get a similar error as before with vtmis-search, I'm guessing the "position" change is just due to daily revisions in the VT output...
```
stoq scan dnetc.exe -a vtmis-search trid
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/bin/stoq", line 11, in <module>
    sys.exit(main())
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/cli.py", line 271, in main
    print(response)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 6777: ordinal not in range(128)
```

I generated an abbreviated install script /w just stoq, it's prereqs, and test runs; but likely as you are seeing no error occurs with it. Looks like I have a few fun days ahead of me paring through my other 1500 lines of normal install script to work out what this is actually related to.

**Comment by mlaferrera** [comment]
I think I've been able to isolate the issue a bit.

Can you change the below lines in plugin file `trid.py`?

From:
```
            p = Popen(
                [self.bin_path, f"-d:{self.trid_defs}", temp_file.name],
                stdout=PIPE,
                stderr=PIPE,
                universal_newlines=True,
            )
```

To:
```
            p = Popen(
                [self.bin_path, f"-d:{self.trid_defs}", temp_file.name],
                stdout=PIPE,
                stderr=PIPE,
                env={'LC_ALL': 'C'},
                universal_newlines=True,
            )
```

**Comment by Kolano** [comment]
That does seem to resolve my problem. I no longer need to externally revise the LANG env variable for the trid plugin to work, and thus can run vtmis-search without the UnicodeEncodeError.

Thanks.

Though, since no changes occurred to vtmis-search there may still be an unaddressed encoding issue. I'll be back to using the default settings, but you may need to watch out for revised encodings causing trouble for stoQ. I don't really have a good perspective though, since my poking was purely focused on getting TrID running.
