### ISSUE TITLE
TrID Results Count

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#54]
**Is your feature request related to a problem? Please describe.**
Default size of TrID results.

**Describe the solution you'd like**
The TrID tool provides an option to set the limit on the number of results it will return...
`-n:nn      Number of matches to show (default: 5)`
It would be nice to provide a trid.stoq option to allow setting that to a value beside the default.

**Comment by mlaferrera** [comment]
Happy to merge a PR if you have time to do this.

**Comment by mlaferrera** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
