### ISSUE TITLE
VTMIS-Search Attribute Name /w Space

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#56]
The VTMIS-Search output can include at least one key with a space in it's name...
`results.workers.vtmis-search.additional_info.sigcheck."link date"`
...which can be problematic for some tools.

Replacing the space with an underscore may be preferable...
`results.workers.vtmis-search.additional_info.sigcheck.link_date`

**Comment by mlaferrera** [comment]
This is how VTMIS returns the results, I don't plan on modifying output from their API.

**Comment by Kolano** [comment]
OK, I'll try to raise it with VT.
