### ISSUE TITLE
TrID Text Files

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#58]
When analyzing text files the trid plugin outputs nothing...
```
"trid": {}
```
The TrID tool outputs...
```
trid example.txt

TrID/32 - File Identifier v2.24 - (C) 2003-16 By M.Pontello
Definitions found:  11309
Analyzing...

Collecting data from file: scene.org.txt

Warning: file seems to be plain text/ASCII
         TrID is best suited to analyze binary files!

100.0% (.BIN) PrintFox/Pagefox bitmap (var. P) (1000/1)
```
or
```
trid test

TrID/32 - File Identifier v2.24 - (C) 2003-16 By M.Pontello
Definitions found:  11309
Analyzing...

Collecting data from file: test

Warning: file seems to be plain text/ASCII
         TrID is best suited to analyze binary files!

       Unknown!

```

It may be be preferable to indicate identification as a text file...
```
"trid": {
	"TXT": [
		{
			"type": "ASCII text"
		}
	]
}
```
...though unclear on matching the TrID format for such. and/or preserve the warning.

**Comment by Kolano** [comment]
What was the changed code here intended to do? It seems to still output nothing when analyzing text files.

It would be preferable to identify such file as TXT, and perhaps include the other types identified (i.e. BIN in the first example above).

**Comment by mlaferrera** [comment]
TrID does not return any signature hits in your example, so there is nothing for stoq to return. This PR ensures better handling of output from TrID and also adds the warning output from TrID as an error in the results. If TRiD returns a signature hit, then it will be added to the results. If not, there won't be any results.

**Comment by Kolano** [comment]
Ah, sorry, missed the errors:{} output.
