### ISSUE TITLE
Plugin Errors and Dependencies

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#62]
I'm having issues with dependencies on plug-ins that error. They seem to still generate worker subsections, just without any populated data. The one example deep-dispatcher uses logic like this to check for plug-in dependencies...
`if 'iocextract' in worker_result:`
...but that is likely to fail when worker_results.iocextract exists, but doesn't include content due to error.

Should the dependency check logic actually look something like...
`if 'iocextract' in worker_result and ('errors' not in worker_result or 'iocextract' not in worker_result.errors):`
...I'm not really clear how to cleanly access errors from within workers / dispatchers. I'm guessing it may be better to just test for empty workers instead.

Also, payload.errors is an object, but payload.workers is an array; how do things work out with errors when a worker is run multiple times? Each plugin's errors is an array so I'd guess each error would appear in that array, but the different structure likely makes it a pain to correlate errors with their related worker.

**Comment by mlaferrera** [comment]
I'm a bit confused as to what the question is. Do you mind clarifying? The example you gave simply checks to see if the payload has already been sent to the `iocextract` plugin, and has not already been processed by the `vtmis-search` plugin. If both tests pass, it will send the payload to the `vtmis-search` worker plugin for scanning. 

`StoqResponse.errors` is a `dict()` of `list()`'s. If a plugin is run multiple times, the error will be appended to said list. For example (obviously completely contrived):

```python
StoqResponse.errors = {
    'vtmis-search': [
        'first error: something didn't work', 
        'second error: something else didn't work'
        ],
    'another-plugin': [
        'this raised an error also'
        ]
    }
```

**Comment by remtcsdev** [comment]
My concern is that workers that error still generate a worker section, so simply testing for the existence of a workers section isn't sufficient to avoid errors when trying to use data from that section (i.e. since it's not populated). It seems one needs to check that the worker section exists and didn't generate an error.

The error handling seems problematic, since there doesn't seem to be a way to correlate which run each error is associated with. I don't think there are any examples of this with current plug-in, but conceivably a plug-in could be run many, many times; so being able to tie an error to a specific run may be important.

Those combine problematically, since one apparently needs to check for errors with a specific plug-in run, but the errors only allow checking that some run caused and error.

**Comment by Kolano** [comment]
My concern is that workers that error still generate a worker section, so simply testing for the existence of a workers section isn't sufficient to avoid errors when trying to use data from that section (i.e. since it's not populated). It seems one needs to check that the worker section exists and didn't generate an error.

The error handling seems problematic, since there doesn't seem to be a way to correlate which run each error is associated with. I don't think there are any examples of this with current plug-in, but conceivably a plug-in could be run many, many times; so being able to tie an error to a specific run may be important.

Those combine problematically, since one apparently needs to check for errors with a specific plug-in run, but the errors only allow checking that some run caused and error.

**Comment by mlaferrera** [comment]
I see. You are correct, right now there is no way to link a specific error to an individual plugin run if it erred more than once. I certainly recognize this is not the ideal way to handle it if the errors need to be accessed programmatically. To avoid errors as you mentioned above, you'll need to ensure your plugins gracefully handle results that may not have the required fields. 

In a future release of stoQ, I'm sure we will work on improving mapping specific errors to an individual run, but for now this is the best path forward.
