### ISSUE TITLE
Vtmis-search not displaying IOC that was sent for analysis in results

### ISSUE THREAD

**Issue by deadh4nd** [PUNCH-Cyber/stoq-plugins-public#64]
When running the vtmis-search plugin, the IOC (or SHA1) are not included in the plugin results.  This makes it difficult to associate the results with the IOC in the decorator stage (or post analysis).  I added the following code on lines 76 and 81 to fix this error in my dev environment:

if response:
    response['ioc'] = ioc

Hope this helps.

**Comment by mlaferrera** [comment]
Thanks @deadh4nd ! I just pushed up an update that should fix this. Please let me know if you notice anything else.

**Comment by deadh4nd** [comment]
Looks great sir!  Thanks for such a quick update.
