### ISSUE TITLE
Smtp plugin does not decode body or html sections

### ISSUE THREAD

**Issue by deadh4nd** [PUNCH-Cyber/stoq-plugins-public#65]
Hi,  While testing a noticed that the smtp plugin does not decode base64 encoded body or html sections of the email.  To resolve this I added the following code at line 108 in the scan() function (also replacing lines 109 & 110):

# Extract the e-mail body, to include HTML if available
            if message.is_multipart():
                retrieve_body = False
                retrieve_html = False
                for part in message.walk():
                    ctype = part.get_content_type()
                    cdispo = str(part.get('Content-Disposition'))
                    #print(type(ctype), ctype, cdispo)
                    if ctype == 'text/plain' and 'attachment' not in cdispo and not retrieve_body:
                        body = str(part.get_payload(decode=True))
                        message_json['body'] = body
                        retrieve_body = True
                    elif ctype == 'text/html' and 'attachment' not in cdispo and not retrieve_html:
                        body_html = str(part.get_payload(decode=True))
                        message_json['body_html'] = body_html
                        retrieve_html = True
            else:
                message_json['body'] = str(message.get_body(preferencelist=('plain')))
                message_json['body_html'] = str(message.get_body(preferencelist=('html')))

**Comment by mlaferrera** [comment]
Thanks again @deadh4nd. I've pushed up a fix for this issue. The latest version of the smtp plugin (v2.0.5) should solve this problem. Please take a look at it and let me know if you see any issues with it.

**Comment by deadh4nd** [comment]
Thanks for the fix sir!  I appreciate it.
