### ISSUE TITLE
peinfo has some unused member methods

### ISSUE THREAD

**Issue by ytreister** [PUNCH-Cyber/stoq-plugins-public#71]
The member method: `_is_suspicious` is not called.  Why did you not call and include this in results?  Same question with `_is_valid`, however I noticed that `peutils.is_valid` does not do anything.

**Comment by mlaferrera** [comment]
Simply overlooked them. The latest version contains the fixes. Thanks!

**Comment by ytreister** [comment]
I made a comment, there was a bug in the fix.

**Comment by mlaferrera** [comment]
Thanks..that was silly of me.
