### ISSUE TITLE
RSDS and NB10 debug info never gets included in peinfo

### ISSUE THREAD

**Issue by ytreister** [PUNCH-Cyber/stoq-plugins-public#72]
`debug_data` data is a byte string, therefore the if conditions `debug_data[:4] == 'RSDS'` and `debug_data[:4] == 'NB10' will never be True, and we will never get the additional GUID, PDB, etc. meta-data. 

I changed the logic to:
```python
if debug_data[:4] == b'RSDS':                
...
elif debug_data[:4] == b'NB10':
...
```
which fixed the problem, but the GUID string does not look great, it has extra `b''` characters in it...

**Comment by mlaferrera** [comment]
Thanks again @ytreister. The latest version should fix this issue.
