### ISSUE TITLE
Vtmis-search Appropriate Handling of Rate Limits

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#75]
Many users of the Vtmis-search plugin are likely to be using public API keys, which limit look-ups to only 4/h, which can easily be exceeded with common stoQ analyses. Even paid packages have similar, though higher limits. Repeated queries when over limits can result in the suspension of VirusTotal accounts.

Revisions are needed to detect rate limit errors, and impose delays preventing repeated look-up until the next timeframe a query will be responded to.

**Comment by mlaferrera** [comment]
Happy to accept PR's for feature requests such as this.

**Comment by Kolano** [comment]
This is also needed for the OPSWAT plug-in.

**Comment by mlaferrera** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
