### ISSUE TITLE
TrID Text Files

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#76]
The TrID plug-in generates errors when analyzing many text file types, rather than more standard "type" output. This can be even more irksome when analyzing archives, as the errors build up across child files resulting in an errors.trid field that can look like...

`"file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII, file seems to be plain text/ASCII"`

It would be nice if it could optionally generate a results.workers.trid.TXT field instead (Though I'm unclear appropriate (#/#) / % data can be populated).

This would probably be more acceptable, if worker errors better aligned with their related payloads and didn't build up.

**Comment by mlaferrera** [comment]
Happy to accept a PR @Kolano. 

As for errors being aligned with payloads, this is fixed in stoQ v3, which should be released as a beta in the coming weeks.

**Comment by mlaferrera** [comment]
v3 of the plugin adds an option to filter warnings such as this. It also supports the `Error` object in stoQ v3 so errors and `payload_id` can be tied together.
