### ISSUE TITLE
OPSWAT URL Problem?

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#77]
I'm having trouble with the OPSWAT plugin. Using...
```
[opswat]
opswat_url = https://api.metadefender.com/v4/file
apikey = XXX
```
...set in stoq.cfg (Note: apikey is the public one), I get the following error on analyses...
```
[2019-12-12 16:20:28,856 ERROR] stoq: deep dispatch:failed to scan (pass 1/1)
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.7/site-packages/stoq/core.py", line 702, in _single_scan
    payload, request_meta
  File "/home/pass/.stoq/plugins/opswat/opswat.py", line 84, in scan
    response.raise_for_status()
  File "/home/pass/.stoq/.venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.metadefender.com/v4/file
```

Performing a curl based request on the same URL...

`curl -X POST https://api.metadefender.com/v4/file -H "apikey: XXX" -H 'content-type: application/octet-stream' -d @file_to_scan`

Returns expected results...
`{"data_id":"bzE5MTIxMkJ5ZnZYQVF4Q1NIa1hEWDBYZ0Fy","status":"inqueue","in_queue":2,"queue_priority":"normal","sha1":"2EF98367FBDCE44619C481DDEEBDD1D3E7D2113E","sha256":"1D32D496E4C58E673EB7693BF4BB39BC2A4FCFD29DEF74EED306DD8827C54903"}`

**Comment by mlaferrera** [comment]
@Kolano You may want to change your API key since you posted it in the initial issue. I've replaced it, but there is no way of telling who has it now.

**Comment by mlaferrera** [comment]
V4 of the opswat API required a specific `content-type` header. Should be good now.

**Comment by Kolano** [comment]
> @Kolano You may want to change your API key since you posted it in the initial issue. I've replaced it, but there is no way of telling who has it now.

As noted initially, that was the public API key Metadefender openly uses with it's online form.

> V4 of the opswat API required a specific content-type header. Should be good now.

Will this need a new release for it to be pulled down automatically with...
`stoq install --github stoq:opswat`
...or does that always pull the newest check-in?

**Comment by mlaferrera** [comment]
You'll want to add `--upgrade` to your install command

**Comment by Kolano** [comment]
This is still broken. I think due to not applying the apikey header with the secondary request.

**Comment by Kolano** [comment]
Also, how would you recommend plug-in's handle setting long term variables for themselves. I'll need to do so for a revision here to account for rate limits (i.e. to set a timeout before requests will restart, based on the 'X-RateLimit-Remaining' and 'X-RateLimit-Reset-In' headers).

**Comment by mlaferrera** [comment]
ok..that should fix the apikey issue. Can you let me know if it's working for you now?

**Comment by Kolano** [comment]
Working now.

**Comment by mlaferrera** [comment]
Thanks!
