### ISSUE TITLE
Recommend using YARA 3.11.0 for stoQ v3

### ISSUE THREAD

**Issue by malvidin** [PUNCH-Cyber/stoq-plugins-public#83]
Changing this plugin requirement to yara-python>=3.11 for stoq >= v3.0.0 would permit consistent use of rules with new keywords.
https://github.com/PUNCH-Cyber/stoq-plugins-public/blob/1640340952d831e0c6205f90a9ca0363ef82e46b/yara/requirements.txt#L1

Like xor, which could replace 254 rules with one that generates all 254. 
https://github.com/PUNCH-Cyber/stoq-plugins-public/blob/1640340952d831e0c6205f90a9ca0363ef82e46b/yara/yarascan/rules/dispatcher.yar#L139
To copy directly from the [YARA docs](https://yara.readthedocs.io/en/stable/writingrules.html#xor-strings):
``` 
        $xor_string = "This program cannot" xor(0x01-0xff)
```

**Comment by mlaferrera** [comment]
Thanks for the feedback. The main reason we have the 254 xor rules in `dispatcher.yar` is because yara does not report back the actual xor key. This presents a problem for automated decoding of the xor encoded payload. Using the multiple rules, the xor key is added to the metadata allowing a follow on plugin to handle decoding the payload properly. If yara ever returns the xor key, I'd be more than happy to update the rules as outlined above.

**Comment by malvidin** [comment]
I apologize, I didn't see if/where `xorkey` was used in this repository or the stoq repository.

**Comment by mlaferrera** [comment]
No worries at all, I really appreciate the feedback. Please keep it coming!

**Comment by malvidin** [comment]
Do you have an open issue in the YARA repository?

**Comment by mlaferrera** [comment]
No -- I don't believe we ever brought it up as an issue.

**Comment by malvidin** [comment]
OK, I added this as an issue.
https://github.com/VirusTotal/yara/issues/1235

**Comment by malvidin** [comment]
As mentioned by @wxsBSD, the information returned by YARA probably won't change.  Would this callback that adds `xorkey` or `xor_info` to the YARA metadata be sufficient?  This keeps the plaintext in one rule, but in two locations.

In the callback below, the metadata include the corresponding string's "$" replaced with "xor_pt_".
meta: xor_pt_a_xor = "AA\nAA"
strings: $a_xor="AA\nAA" xor

```
import re
import yara

XOR_FIRST_MATCH_ONLY = False

def xor_meta_callback(data, first_match_only=XOR_FIRST_MATCH_ONLY):
    xor_info = []
    xor_pt = {re.sub(r'xor_pt_', '$', k): v for k, v in data['meta'].items() if k.startswith("xor_pt_")}
    if len(xor_pt) != 0:
        key = None
        for offset, label, match in data['strings']:
            if label not in xor_pt:
                pass
            if xor_pt[label] == match:
                key = 0
            else:
                keys = set([a ^ b for (a, b) in zip(a_pt, match)])
                if len(keys) == 1:
                    key = keys.pop()
                    xor_info.append((offset, label, key))
                    if first_match_only:
                        data['meta']['xorkey'] = key
                        return yara.CALLBACK_CONTINUE
    data['meta']['xor_info'] = repr(xor_info)
    return yara.CALLBACK_CONTINUE

a_pt= b"AA\nAA"
mydata = b"BB\tBBAA\nAA"
myrule = r'''
rule test_xor
{
  meta:
    test = "value"
    xor_pt_a_xor = "AA\nAA"
  strings:
    $a_xor="AA\nAA" xor
  condition:
    all of them
}
'''

yr = yara.compile(source=myrule)
yml = yr.match(data=mydata, callback=xor_meta_callback)

print(yml[0].meta)
assert yml[0].meta['xorkey'] == 3
```

**Comment by malvidin** [comment]
What are your thoughts on this?

https://github.com/PUNCH-Cyber/stoq-plugins-public/blob/1640340952d831e0c6205f90a9ca0363ef82e46b/yara/yarascan/yarascan.py#L98

```
        matches = rules.match(data=content, callback=_xor_meta_callback, timeout=self.timeout)
```

```
XOR_FIRST_MATCH_ONLY = True

def _xor_meta_callback(data, first_match_only=XOR_FIRST_MATCH_ONLY):
    xor_info = []
    xor_pt = {re.sub(r'xor_pt_', '$', k): v for k, v in data['meta'].items() if k.startswith("xor_pt_")}
    if len(xor_pt) != 0:
        key = None
        for offset, label, match in data['strings']:
            if label not in xor_pt:
                pass
            if xor_pt[label] == match:
                key = 0
            else:
                keys = set([a ^ b for (a, b) in zip(a_pt, match)])
                if len(keys) == 1:
                    key = keys.pop()
                    xor_info.append((offset, label, key))
                    if first_match_only:
                        data['meta']['xorkey'] = key
                        return yara.CALLBACK_CONTINUE
    data['meta']['xor_info'] = repr(xor_info)
    return yara.CALLBACK_CONTINUE

```
